### ISSUE TITLE
nix flake show error

### ISSUE THREAD

**Issue by phanirithvij** [Baitinq/nixos-config#12]
```shell
$ nix --version
nix (Nix) 2.24.10
$ nix flake show
error: [json.exception.parse_error.101] parse error at line 1, column 1: attempting to parse an empty input; check that your input string or stream contains the expected JSON
```

**Comment by Baitinq** [comment]
Hi @phanirithvij !

This is caused because the `flake.lock` and `secrets/*` files are encrypted for privacy reasons, so nix cant actually evaluate them unless decrypted. I'd recommend deleting them and trying again! (you'll get some secrets errors as the files will be missing but you can very easily recreate them or delete the relevant modules).

Hope this helps!

**Comment by phanirithvij** [comment]
ok I didn't realise. I will check it out later
